In [2]:
# @title importing
import requests
import pandas as pd
season_id = '2023-24'
per_mode = 'Totals'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight='
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']

columns_list = [
        #season_id=season_id
        'player_id',
        'player_name',
        'nickname',
        'team_id',
        'team_abbreviation',
        'age',
        'gp',
        'w',
        'l',
        'w_pct',
        'min',
        'fgm',
        'fga',
        'fg_pct',
        'fg3m',
        'fg3a',
        'fg3_pct',
        'ftm',
        'fta',
        'ft_pct',
        'oreb',
        'dreb',
        'reb',
        'ast',
        'tov',
        'stl',
        'blk',
        'blka',
        'pf',
        'pfd',
        'pts',
        'plus_minus',
        'nba_fantasy_pts',
        'dd2',
        'td3',
        'gp_rank',
        'w_rank',
        'l_rank',
        'w_pct_rank',
        'min_rank',
        'fgm_rank',
        'fga_rank',
        'fg_pct_rank',
        'fg3m_rank',
        'fg3a_rank',
        'fg3_pct_rank',
        'ftm_rank',
        'fta_rank',
        'ft_pct_rank',
        'oreb_rank',
        'dreb_rank',
        'reb_rank',
        'ast_rank',
        'tov_rank',
        'stl_rank',
        'blk_rank',
        'blka_rank',
        'pf_rank',
        'pfd_rank',
        'pts_rank',
        'plus_minus_rank',
        'nba_fantasy_pts_rank',
        'dd2_rank',
        'td3_rank',
        'cfid',
        'cfparams',
]
nba_df = pd.DataFrame(player_info, columns = columns_list)

nba_df.sample(10)

nba_df.to_csv('player_general_traditional_2023-24.csv', index=False)

In [3]:
# @title 2023-24 csv generation
new = pd.read_csv('player_general_traditional_2023-24.csv', usecols=lambda x: x not in ["player_name", "nickname", "team_id", "team_abbreviation"])
new['allstar'] = 0

allstar_ids = [2544, 1629029, 201142, 1628983, 203999, 1626164, 201939, 203076, 1630162, 202331, 202695, 1626157,
               1628389, 203507, 1630169, 203081, 1628369, 1631094, 1627759, 1628973, 1630178, 1628378, 203944, 203954]
for player_id in allstar_ids:
  new.loc[new['player_id'] == player_id, 'allstar'] = 1

new = new.drop("player_id", axis='columns')

new.head()

,age,gp,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,...,pf_rank,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,cfid,cfparams,allstar
0,23.0,42,27,15,0.643,310.900000,54,121,0.446,13,...,211,148,415,385,192,400,257,38,405,0
1,24.0,56,35,21,0.625,614.281667,83,196,0.423,69,...,121,223,375,313,145,369,257,38,343,0
2,20.0,20,8,12,0.400,170.730000,18,62,0.290,10,...,121,77,519,450,396,480,257,38,469,0
3,28.0,73,49,24,0.671,2296.810000,398,716,0.556,40,...,520,457,52,93,13,79,54,38,87,0
4,27.0,78,39,39,0.500,1269.296667,186,417,0.446,84,...,335,419,238,216,123,243,257,38,233,0

In [14]:
# @title Logistic Regression Model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# LOGISTIC REGRESSION

X = new.drop(['allstar'], axis=1)
y = new['allstar']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter = 700)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# accuracy around 99%

Accuracy: 0.991304347826087

In [5]:
# @title 2022-23 Season CSV Generation
season_id = '2022-23'
per_mode = 'Totals'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight='
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']

columns_list = [
        #season_id=season_id
        'player_id',
        'player_name',
        'nickname',
        'team_id',
        'team_abbreviation',
        'age',
        'gp',
        'w',
        'l',
        'w_pct',
        'min',
        'fgm',
        'fga',
        'fg_pct',
        'fg3m',
        'fg3a',
        'fg3_pct',
        'ftm',
        'fta',
        'ft_pct',
        'oreb',
        'dreb',
        'reb',
        'ast',
        'tov',
        'stl',
        'blk',
        'blka',
        'pf',
        'pfd',
        'pts',
        'plus_minus',
        'nba_fantasy_pts',
        'dd2',
        'td3',
        'gp_rank',
        'w_rank',
        'l_rank',
        'w_pct_rank',
        'min_rank',
        'fgm_rank',
        'fga_rank',
        'fg_pct_rank',
        'fg3m_rank',
        'fg3a_rank',
        'fg3_pct_rank',
        'ftm_rank',
        'fta_rank',
        'ft_pct_rank',
        'oreb_rank',
        'dreb_rank',
        'reb_rank',
        'ast_rank',
        'tov_rank',
        'stl_rank',
        'blk_rank',
        'blka_rank',
        'pf_rank',
        'pfd_rank',
        'pts_rank',
        'plus_minus_rank',
        'nba_fantasy_pts_rank',
        'dd2_rank',
        'td3_rank',
        'cfid',
        'cfparams',
]
nba_df = pd.DataFrame(player_info, columns = columns_list)

nba_df.sample(10)

nba_df.to_csv('player_general_traditional_2022-23.csv', index=False)
nba_df.sample(10)

,player_id,player_name,nickname,team_id,team_abbreviation,age,gp,w,l,w_pct,...,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,cfid,cfparams
80,1630175,Cole Anthony,Cole,1610612753,ORL,23.0,60,28,32,0.467,...,111,336,441,149,132,327,143,192,39,143
472,1628425,Sterling Brown,Sterling,1610612747,LAL,28.0,4,2,2,0.500,...,491,42,38,526,535,251,517,253,39,520
18,2738,Andre Iguodala,Andre,1610612744,GSW,39.0,8,3,5,0.375,...,429,1,74,445,495,157,471,253,39,474
407,1630846,Olivier Sarr,Olivier,1610612760,OKC,24.0,9,5,4,0.556,...,385,1,99,426,466,190,465,192,39,466
262,1630692,Jordan Goodwin,Jordan,1610612764,WAS,24.0,62,22,40,0.355,...,144,375,285,225,258,462,225,253,39,238
246,202710,Jimmy Butler,Jimmy,1610612748,MIA,33.0,64,35,29,0.547,...,178,487,254,16,35,144,29,56,39,39
39,1629626,Bol Bol,Bol,1610612753,ORL,23.0,70,26,44,0.371,...,19,306,282,208,189,478,159,92,39,166
280,1630577,Julian Champagnie,Julian,1610612759,SAS,22.0,17,7,10,0.412,...,385,131,123,414,373,409,402,192,39,392
177,1630529,Herbert Jones,Herbert,1610612740,NOP,24.0,66,31,35,0.470,...,75,412,508,119,179,72,147,253,39,158
297,1626162,Kelly Oubre Jr.,Kelly,1610612766,CHA,27.0,48,16,32,0.333,...,207,495,406,73,102,522,149,130,39,137

In [17]:
# @title Testing My Model on 2022-23 Dataset
unseen_data = pd.read_csv('player_general_traditional_2022-23.csv', usecols=lambda x: x not in ["player_name", "nickname", "team_id", "team_abbreviation"])
unseen_data['allstar'] = 0

allstar_ids = [2544, 1629029, 203954, 202681, 203999, 1627759, 202331, 1630169, 1628991, 203944, 201939, 1629627,
               203507, 1628374, 1628378, 1629630, 1628369, 1628389, 1628983, 201942, 201950, 203081, 1627734, 201142]
for player_id in allstar_ids:
  unseen_data.loc[unseen_data['player_id'] == player_id, 'allstar'] = 1

unseen_data = unseen_data.drop("player_id", axis='columns')



X_unseen = unseen_data.drop(['allstar'], axis=1)  # Assuming 'player_id' is not a feature

y_pred_unseen = model.predict(X_unseen)

unseen_data['predicted_allstar'] = y_pred_unseen

pd.options.display.max_columns = None
pd.options.display.max_rows = None

differences = int((unseen_data['allstar'] != unseen_data['predicted_allstar']).sum() / 2)

print("Number of differences between 'allstar' and 'predicted_allstar':", differences, "\n")
differences_df = unseen_data[unseen_data['allstar'] != unseen_data['predicted_allstar']]

num_rows = same_df.shape[0]

print("My accuracy of this specific run was: ", num_rows/(num_rows+differences))

#print("IDs of players where 'allstar' and 'predicted_allstar' values differ:")
#print(differences_df['player_id'])

#unseen_data.head(1000)

differences_df = unseen_data[unseen_data['allstar'] != unseen_data['predicted_allstar']]
same_df = unseen_data[(unseen_data['allstar'] == 1) & (unseen_data['predicted_allstar'] == 1)]


# Print the first few rows of the filtered DataFrame
print("Rows where 'allstar' and 'predicted_allstar' values are the same:")
#print(same_df.to_string(index=False, max_rows=100))  # Adjust max_rows as needed
same_df.head(100)

Number of differences between 'allstar' and 'predicted_allstar': 5

My accuracy of this specific run was:  0.7916666666666666
Rows where 'allstar' and 'predicted_allstar' values are the same:

,age,gp,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,tov,stl,blk,blka,pf,pfd,pts,plus_minus,nba_fantasy_pts,dd2,td3,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,fgm_rank,fga_rank,fg_pct_rank,fg3m_rank,fg3a_rank,fg3_pct_rank,ftm_rank,fta_rank,ft_pct_rank,oreb_rank,dreb_rank,reb_rank,ast_rank,tov_rank,stl_rank,blk_rank,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,cfid,cfparams,allstar,predicted_allstar
29,25.0,75,40,35,0.533,2597.993333,602,1114,0.540,1,12,0.083,324,402,0.806,184,504,688,240,187,88,61,49,208,360,1529,117,2974.6,31,0,2756.0,70,74,420,217,18,17,36,91,459,420,487,26,25,196,20,16,15,84,28,26,37,476,508,18,27,91,15,18,39,21,1,1
90,32.0,58,27,31,0.466,2106.590000,556,1202,0.463,244,658,0.371,510,558,0.914,44,233,277,425,191,50,18,46,109,413,1866,105,2848.9,16,2,2948.0,240,238,357,343,89,29,24,246,5,4,179,6,7,44,211,127,152,23,25,138,207,466,333,6,11,95,21,41,11,15,1,1
130,27.0,79,47,32,0.595,2735.555000,577,938,0.615,31,83,0.373,325,438,0.742,251,722,973,573,230,65,39,64,279,373,1510,212,3619.1,65,14,3295.0,27,22,377,122,6,24,60,43,283,301,168,24,18,314,4,2,1,5,9,82,80,514,539,15,29,42,5,1,2,8,1,1
132,26.0,68,44,24,0.647,2432.380000,679,1402,0.484,245,635,0.386,319,368,0.867,63,226,289,301,180,99,27,56,168,279,1922,338,2918.3,5,0,3009.0,133,40,238,80,30,8,5,193,4,9,130,27,29,91,134,139,132,52,33,13,140,498,461,34,8,17,16,105,39,11,1,1
166,28.0,63,47,16,0.746,2023.615000,707,1278,0.553,47,171,0.275,498,772,0.645,137,605,742,359,246,52,51,82,197,570,1959,341,3450.9,46,6,3313.0,189,22,153,20,102,4,17,78,236,200,413,7,1,436,40,5,9,36,6,132,51,528,502,1,5,15,6,4,5,7,1,1
193,23.0,61,40,21,0.656,1948.348333,566,1214,0.466,92,300,0.307,372,497,0.748,61,296,357,493,206,66,16,84,100,380,1596,302,2803.9,20,7,2702.0,214,74,200,68,117,26,22,239,135,103,371,13,12,306,142,70,84,14,14,75,228,530,307,13,24,21,23,30,4,26,1,1
235,26.0,67,46,21,0.687,2404.918333,679,1383,0.491,163,487,0.335,263,344,0.765,78,381,459,232,197,75,26,77,172,272,1784,256,2788.8,13,0,2840.0,145,32,200,42,35,8,8,175,35,28,289,40,34,266,97,40,49,90,19,51,144,524,467,39,14,27,24,50,39,17,1,1
238,25.0,74,52,22,0.703,2732.196667,727,1559,0.466,240,686,0.350,531,622,0.854,78,571,649,342,213,78,51,58,160,401,2225,470,3690.8,31,1,3714.0,79,8,214,32,7,2,1,238,6,2,247,4,6,112,97,8,22,39,12,46,51,502,450,7,1,6,4,18,17,1,1,1
251,29.0,66,43,23,0.652,2284.106667,728,1328,0.548,66,200,0.330,661,771,0.857,113,557,670,274,226,66,112,91,205,511,2183,424,3706.0,39,1,3549.0,162,53,226,75,54,1,13,83,180,178,320,2,2,103,58,9,18,66,10,75,8,535,507,2,2,8,3,9,17,3,1,1
277,33.0,67,50,17,0.746,2182.540000,490,1023,0.479,158,411,0.384,152,177,0.859,79,262,341,495,197,79,25,45,116,161,1290,481,2556.7,16,0,2492.0,145,13,162,19,71,44,46,209,43,44,137,97,109,101,95,98,93,12,19,45,154,463,352,100,52,5,43,41,39,41,1,1
281,28.0,77,44,33,0.571,2737.251667,658,1432,0.459,218,636,0.343,402,531,0.757,141,626,767,316,216,49,21,57,233,378,1936,170,3324.4,40,0,3377.0,46,40,385,149,5,11,4,253,8,8,269,10,10,284,37,4,6,50,11,144,178,499,529,14,7,59,8,6,39,5,1,1
308,34.0,47,34,13,0.723,1671.756667,483,862,0.560,93,230,0.404,307,334,0.919,17,296,313,235,156,34,67,25,99,272,1366,258,2241.1,5,1,2209.0,311,149,123,26,165,46,77,74,131,153,76,31,37,40,356,70,114,87,45,226,31,358,299,39,42,26,63,105,17,61,1,1
331,26.0,66,32,34,0.485,2272.486667,571,1144,0.499,200,510,0.392,349,399,0.875,130,440,570,123,127,42,38,65,137,297,1691,163,2672.5,28,0,2744.0,162,178,403,310,58,25,29,156,20,20,108,20,26,78,43,26,29,173,73,181,82,517,399,28,16,63,34,21,39,24,1,1
332,38.0,55,30,25,0.545,1953.940000,609,1219,0.500,121,377,0.321,251,327,0.768,65,392,457,375,178,50,32,47,88,273,1590,214,2768.9,18,2,2707.0,267,207,256,195,115,16,21,155,86,63,344,44,39,261,128,37,51,32,35,138,108,471,273,38,25,39,25,35,11,25,1,1
340,24.0,66,33,33,0.500,2390.471667,719,1449,0.496,185,541,0.342,515,694,0.742,54,515,569,529,236,90,33,44,166,481,2138,128,3747.3,36,10,3667.0,162,162,385,264,36,3,3,160,26,18,270,5,4,313,172,14,30,8,8,23,102,459,457,4,3,83,2,11,3,2,1,1
399,28.0,69,48,21,0.696,2323.006667,646,1022,0.632,57,149,0.383,341,415,0.822,167,650,817,678,247,87,47,49,174,392,1690,640,3842.4,58,29,3510.0,123,16,200,36,47,13,47,34,208,220,140,23,22,169,25,3,3,2,5,28,62,476,470,11,17,1,1,2,1,4,1,1
424,33.0,56,32,24,0.571,1938.891667,459,1004,0.457,158,426,0.371,256,294,0.871,45,297,342,288,176,83,20,37,159,230,1332,157,2307.4,8,1,2326.0,253,178,238,149,122,55,50,261,43,39,178,42,49,85,205,69,92,58,36,32,191,429,444,53,47,66,54,80,17,51,1,1
463,24.0,68,33,35,0.485,2415.985000,704,1381,0.510,58,168,0.345,669,739,0.905,59,270,329,371,192,112,65,97,192,491,2135,149,3425.3,3,0,3247.0,133,162,420,309,33,6,9,131,204,203,262,1,3,50,148,90,102,33,24,6,32,538,495,3,4,73,7,130,39,9,1,1
471,35.0,56,30,26,0.536,1941.151667,559,1133,0.493,273,639,0.427,257,281,0.915,39,302,341,352,179,52,20,41,117,219,1648,268,2622.2,12,1,2758.0,253,207,273,212,120,28,31,168,3,6,42,41,52,43,235,66,93,37,34,132,191,454,354,60,21,25,37,53,17,20,1,1

In [ ]:
# @title Print Differences in Model

print("Rows where 'allstar' and 'predicted_allstar' values differ:")
differences_df.head()

Rows where 'allstar' and 'predicted_allstar' values differ:

,age,gp,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,tov,stl,blk,blka,pf,pfd,pts,plus_minus,nba_fantasy_pts,dd2,td3,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,fgm_rank,fga_rank,fg_pct_rank,fg3m_rank,fg3a_rank,fg3_pct_rank,ftm_rank,fta_rank,ft_pct_rank,oreb_rank,dreb_rank,reb_rank,ast_rank,tov_rank,stl_rank,blk_rank,blka_rank,pf_rank,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,cfid,cfparams,allstar,predicted_allstar
22,30.0,56,31,25,0.554,1904.510000,542,962,0.563,19,74,0.257,348,444,0.784,195,507,702,148,122,59,114,58,146,329,1451,205,2912.4,40,0,2666.0,253,191,256,178,127,32,55,69,323,310,427,21,16,226,17,15,12,147,83,102,7,502,419,22,36,46,17,6,39,29,0,1
23,21.0,79,40,39,0.506,2841.455000,707,1541,0.459,213,578,0.369,319,422,0.756,47,411,458,350,259,125,58,59,186,278,1946,97,3310.6,9,0,3333.0,27,74,472,261,2,4,2,255,10,11,187,27,20,286,197,34,50,38,2,3,44,505,484,35,6,102,9,70,39,6,0,1
110,33.0,74,37,37,0.500,2681.610000,657,1303,0.504,46,142,0.324,456,523,0.872,34,309,343,377,153,83,36,62,186,396,1816,67,2997.1,6,0,2820.0,79,110,450,264,11,12,16,138,239,228,338,9,11,80,257,62,91,31,47,32,89,508,484,9,13,124,14,92,39,18,1,0
220,33.0,58,39,19,0.672,2135.005000,371,842,0.441,161,418,0.385,313,361,0.867,40,314,354,618,195,71,31,52,112,267,1216,277,2678.8,36,5,2553.0,240,89,176,53,80,94,80,320,38,41,133,30,30,90,230,61,85,3,21,61,111,482,338,43,64,24,33,11,6,37,0,1
225,23.0,63,41,22,0.651,1787.503333,416,822,0.506,100,282,0.355,241,306,0.788,108,318,426,60,107,65,189,66,227,243,1173,366,2429.2,7,0,2267.0,189,65,214,76,147,74,84,136,118,117,233,48,46,220,62,59,56,291,102,82,2,520,524,50,69,11,48,86,39,56,1,0